### ISSUE TITLE
在页面打印时设置打印区域和页面的幅面设置

### ISSUE THREAD

**Issue by sikma** [sikma/Solution#9]
在网页打印的过程中，可能会有部分区域不想打印，可以现在网页的CSS中加入如下代码
``` css
@media print {
  .invoice_list {
   display: none;
  }
}

    @page{
        size: B5 landscape;
    margin:0;
    }
```

其中**media print**是CSS中的一个页面规则，用来控制打印动作，.invoice_list是规则中的一个自定义子规则，花括号内是规则的用途`display: none;`就是不打印的意思，在页面中不想打印的区域用`<div class=invoice_list>.......</div>`来标记；**page**用来定义页面打印时的页面设置规则，这个CSS里面的默认是B5,边缘留白空间为0
